# Generated by Django 4.2.13 on 2024-08-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="category",
            field=models.CharField(
                choices=[
                    ("attributes", "Attributes"),
                    ("abilities", "Abilities"),
                    ("advantages", "Advantages"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="stat",
            name="stat_type",
            field=models.CharField(
                choices=[
                    ("attribute", "Attribute"),
                    ("ability", "Ability"),
                    ("advantage", "Advantage"),
                    ("background", "Background"),
                    ("discipline", "Discipline"),
                    ("gift", "Gift"),
                    ("sphere", "Sphere"),
                    ("rote", "Rote"),
                    ("art", "Art"),
                    ("edge", "Edge"),
                    ("discipline", "Discipline"),
                    ("path", "Path"),
                    ("power", "Power"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
