# Generated by Django 4.2.13 on 2024-08-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0002_alter_stat_category_alter_stat_stat_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="stat",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stat",
            name="game_line",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="stat",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="stat",
            name="stat_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="stat",
            name="values",
            field=models.JSONField(default=list),
        ),
    ]
