# Generated by Django 4.2.13 on 2024-08-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0003_alter_stat_category_alter_stat_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
