# Generated by Django 4.2.13 on 2024-08-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0004_alter_stat_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="stat",
            name="lock_string",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
