# Generated by Django 4.2.13 on 2024-08-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0005_stat_lock_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="values",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
