# Generated by Django 4.2.13 on 2024-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0006_alter_stat_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="stat",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stat",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stat",
            name="splat",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="category",
            field=models.CharField(
                choices=[
                    ("attributes", "Attributes"),
                    ("abilities", "Abilities"),
                    ("advantages", "Advantages"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="stat",
            name="stat_type",
            field=models.CharField(
                choices=[
                    ("attribute", "Attribute"),
                    ("ability", "Ability"),
                    ("advantage", "Advantage"),
                    ("background", "Background"),
                    ("discipline", "Discipline"),
                    ("gift", "Gift"),
                    ("sphere", "Sphere"),
                    ("rote", "Rote"),
                    ("art", "Art"),
                    ("edge", "Edge"),
                    ("discipline", "Discipline"),
                    ("path", "Path"),
                    ("power", "Power"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
