# Generated by Django 4.2.13 on 2024-08-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0016_alter_stat_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="category",
            field=models.CharField(
                choices=[
                    ("attributes", "Attributes"),
                    ("abilities", "Abilities"),
                    ("advantages", "Advantages"),
                    ("backgrounds", "Backgrounds"),
                    ("powers", "Powers"),
                    {"Merits", "merits"},
                    ("flaws", "Flaws"),
                    ("traits", "Traits"),
                    ("identity", "Identity"),
                    ("virtues", "Virtues"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
