# Generated by Django 4.2.13 on 2024-08-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0017_alter_stat_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="stat",
            name="instanced",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
