# Generated by Django 4.2.13 on 2024-08-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0019_alter_stat_category_alter_stat_stat_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="stat_type",
            field=models.CharField(
                choices=[
                    ("attribute", "Attribute"),
                    ("ability", "Ability"),
                    ("advantage", "Advantage"),
                    ("background", "Background"),
                    ("lineage", "Lineage"),
                    ("discipline", "Discipline"),
                    ("gift", "Gift"),
                    ("sphere", "Sphere"),
                    ("rote", "Rote"),
                    ("art", "Art"),
                    ("splat", "Splat"),
                    ("edge", "Edge"),
                    ("discipline", "Discipline"),
                    ("path", "Path"),
                    ("power", "Power"),
                    ("other", "Other"),
                    ("virtue", "Virtue"),
                    ("vice", "Vice"),
                    ("merit", "Merit"),
                    ("flaw", "Flaw"),
                    ("trait", "Trait"),
                    ("skill", "Skill"),
                    ("knowledge", "Knowledge"),
                    ("knowlege-secondary", "Secondary Knowledge"),
                    ("telent-secondary", "Secondary Talent"),
                    ("skill-secondary", "Secondary Skill"),
                    ("talent", "Talent"),
                    ("specialty", "Specialty"),
                    ("other", "Other"),
                    ("physical", "Physical"),
                    ("social", "Social"),
                    ("mental", "Mental"),
                    ("personal", "Personal"),
                    ("supernatural", "Supernatural"),
                    ("moral", "Moral"),
                    ("inhuman", "Inhuman"),
                    ("temporary", "Temporary"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
