# Generated by Django 4.2.13 on 2024-08-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0020_alter_stat_stat_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="category",
            field=models.CharField(
                choices=[
                    ("attributes", "Attributes"),
                    ("abilities", "Abilities"),
                    ("advantages", "Advantages"),
                    ("backgrounds", "Backgrounds"),
                    ("powers", "Powers"),
                    ("merits", "Merits"),
                    ("flaws", "Flaws"),
                    ("traits", "Traits"),
                    ("identity", "Identity"),
                    ("virtues", "Virtues"),
                    ("pools", "Pools"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
