# Generated by Django 4.2.13 on 2024-08-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0021_alter_stat_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="stat",
            name="default",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
