# Generated by Django 4.2.16 on 2024-10-07 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
        ("wod20th", "0023_charactersheet_note"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="note",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="note",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="objects.objectdb",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AlterField(
            model_name="note",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together={("character", "name")},
        ),
        migrations.RemoveField(
            model_name="note",
            name="character_sheet",
        ),
    ]
